### ISSUE TITLE
allow registries to specify per-julia-version branches

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Pkg3.jl#127]
In Pkg2 we checkout `metadata-v2` instead of `master`. The idea there was that if we made an incompatible change to the metadata format, the `metadata-v2` branch could continue to use the old format while a newer branch, presumably `metadata-v3`, would use the new format. Instead of using a strange branch name, we can get the same future-proofing effect by allowing as section in the `registry.toml` file:
```toml
name = "Uncurated"
uuid = "c2463f1f-d711-5ace-9c99-4f745c283c7e"
repo = "https://github.com/JuliaRegistries/Uncurated.git"

description = """
Official uncurated Julia package registry where people can
register any package they want without too much debate about
naming and without enforced standards on documentation or
testing. We nevertheless encourage documentation, testing and
some amount of consideration when choosing package names.

[branch]
"1.0-1.3" = "release-1.3"
"1.4-1.5" = "release-1.5"
"""
```
`VERSION` is matched against the version spec of each entry in the `[branch]` section and if there is a match, the branch name (or commit) on the right is checked out instead of the default branch. If the `[branch]` section doesn't exist or `VERSION` doesn't match any of the patterns, then the default branch `master` is used.
